// corpus.js — GENERATED by build_corpus.py from corpus_src.py. Do not edit by hand.
export const LEVELS = [
 {
  "n": 1,
  "name": "First moves",
  "blurb": "Two or three chords: I, IV and V. Hear home, the lift, and the lean."
 },
 {
  "n": 2,
  "name": "Four-chord pop",
  "blurb": "I, IV, V and vi in every order pop has tried."
 },
 {
  "n": 3,
  "name": "Minor & modal",
  "blurb": "Minor keys, Dorian loops, and the flat seven."
 },
 {
  "n": 4,
  "name": "Bass vs. root",
  "blurb": "Inversions and pedal notes: the bass is not always the root. Name the chord; use the bass hint if you need it."
 },
 {
  "n": 5,
  "name": "Borrowed chords",
  "blurb": "bVII, bVI, III and other visitors from outside the key."
 },
 {
  "n": 6,
  "name": "Club & synth",
  "blurb": "Electronic and synth-pop loops, often with minor v or major IV."
 },
 {
  "n": 7,
  "name": "Long form",
  "blurb": "Six to eight chords with walking bass lines. One listen if you can."
 }
];

export const SONGS = [
 {
  "id": "born-in-the-u-s-a-bruce-springsteen",
  "title": "Born in the U.S.A.",
  "artist": "Bruce Springsteen",
  "year": 1984,
  "key": "B",
  "tempo": 122,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 8
   }
  ],
  "src": "std",
  "note": "Two chords for the whole song. The synth riff sits on top; listen for the bass dropping from B to E and back.",
  "spotify": "spotify:track:0dOg1ySSI7NkpAe89Zo0b9",
  "art": "https://i.scdn.co/image/ab67616d00001e02a43a6482e327d623bb0c0f77"
 },
 {
  "id": "feelin-alright-joe-cocker",
  "title": "Feelin' Alright",
  "artist": "Joe Cocker",
  "year": 1969,
  "key": "C",
  "tempo": 108,
  "section": "whole song",
  "start": 0,
  "dur": 22,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I to IV, back and forth, forever. The piano and bass both move up a fourth on every change.",
  "spotify": "spotify:track:0Jl5bIEve3A4axcjY3EgDZ",
  "art": "https://i.scdn.co/image/ab67616d00001e025bb09aa81ffb17ccf902629f",
  "ug": "https://tabs.ultimate-guitar.com/tab/joe-cocker/feeling-alright-official-2189955"
 },
 {
  "id": "everyday-people-sly-the-family-stone",
  "title": "Everyday People",
  "artist": "Sly & The Family Stone",
  "year": 1969,
  "key": "G",
  "tempo": 98,
  "section": "verse",
  "start": 0,
  "dur": 22,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4,
    "bass": "5"
   }
  ],
  "src": "official",
  "note": "The bass never moves: C over G, so the change is all in the chord on top. Hear it as home, then a lift.",
  "spotify": "spotify:track:4ZVZBc5xvMyV3WzWktn8i7",
  "art": "https://i.scdn.co/image/ab67616d00001e02147e35fd67f22f92cb587c3b",
  "ug": "https://tabs.ultimate-guitar.com/tab/sly-the-family-stone/everyday-people-official-3756152"
 },
 {
  "id": "what-i-got-sublime",
  "title": "What I Got",
  "artist": "Sublime",
  "year": 1996,
  "key": "D",
  "tempo": 92,
  "section": "verse",
  "start": 0,
  "dur": 22,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "D to G the whole way through. Sing the bass: root, then up a fourth.",
  "spotify": "spotify:track:3B4q6KbHbGV51HO3GznBFF",
  "art": "https://i.scdn.co/image/ab67616d00001e028fc4b0dcfb9509553f195c85",
  "ug": "https://tabs.ultimate-guitar.com/tab/sublime/what-i-got-official-2483847"
 },
 {
  "id": "heroin-the-velvet-underground",
  "title": "Heroin",
  "artist": "The Velvet Underground",
  "year": 1967,
  "key": "Db",
  "tempo": 72,
  "section": "intro / verse",
  "start": 0,
  "dur": 28,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "Two chords, no drums to hide behind. The viola drone stays put while the bass moves Db to Gb (the band is tuned down a half step).",
  "spotify": "spotify:track:5by3w3NXvwDpV9FBSOR35u",
  "art": "https://i.scdn.co/image/ab67616d00001e0298260c528e6eec9dd431c1d7",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-velvet-underground/heroin-official-3023045"
 },
 {
  "id": "you-can-t-always-get-what-you-want-the-rolling-stones",
  "title": "You Can't Always Get What You Want",
  "artist": "The Rolling Stones",
  "year": 1969,
  "key": "C",
  "tempo": 84,
  "section": "verse",
  "start": 48,
  "dur": 24,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 8,
    "bass": "3"
   }
  ],
  "src": "official",
  "note": "C to F under the verse, with the F played over A so the bass only drops a minor third. Same move as Feelin' Alright, slower and with a choir.",
  "spotify": "spotify:track:6lFZbCc7pn6Lme1NP7qQqQ",
  "art": "https://i.scdn.co/image/ab67616d00001e022af30c881bb23cfb82a8cf99",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-rolling-stones/you-cant-always-get-what-you-want-official-2538216"
 },
 {
  "id": "jambalaya-on-the-bayou-hank-williams",
  "title": "Jambalaya (On the Bayou)",
  "artist": "Hank Williams",
  "year": 1998,
  "key": "C",
  "tempo": 128,
  "section": "verse",
  "start": 0,
  "dur": 20,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "V",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "Country two-chord: home (I) and away (V). The V wants to fall back to I; that pull is the sound to learn.",
  "spotify": "spotify:track:2KJOfVTxWkbtRMGByeEQ7V",
  "art": "https://i.scdn.co/image/ab67616d00001e028326fd3fdf926786d2b0525f",
  "ug": "https://tabs.ultimate-guitar.com/tab/hank-williams/jambalaya-official-3050122"
 },
 {
  "id": "three-little-birds-bob-marley-the-wailers",
  "title": "Three Little Birds",
  "artist": "Bob Marley & The Wailers",
  "year": 2002,
  "key": "A",
  "tempo": 76,
  "section": "chorus",
  "start": 16,
  "dur": 25,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I for two bars, IV for one, back to I. The V (E) only shows up in the verse; the chorus never leaves I and IV.",
  "spotify": "spotify:track:7vggqxNKwd6xdRoYS0pQtM",
  "art": "https://i.scdn.co/image/ab67616d00001e02413a6c2c7b296d98171e5e21",
  "ug": "https://tabs.ultimate-guitar.com/tab/bob-marley/three-little-birds-official-2072761"
 },
 {
  "id": "chasing-cars-snow-patrol",
  "title": "Chasing Cars",
  "artist": "Snow Patrol",
  "year": 2006,
  "key": "A",
  "tempo": 104,
  "section": "verse",
  "start": 18,
  "dur": 26,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "V",
    "beats": 8,
    "bass": "3"
   },
   {
    "rn": "IV",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "A, then E over G#, then D. The chart spells the second chord E/G#, but it never resolves to A; it passes. It shares two notes and its bass with C#m, so iii is an equally fair name, and the app accepts either.",
  "spotify": "spotify:track:5hnyJvgoWiQUYZttV4wXy6",
  "art": "https://i.scdn.co/image/ab67616d00001e025da2756220da9b6f17924f8f",
  "ug": "https://tabs.ultimate-guitar.com/tab/snow-patrol/chasing-cars-official-1918437"
 },
 {
  "id": "la-bamba-ritchie-valens",
  "title": "La Bamba",
  "artist": "Ritchie Valens",
  "year": 2022,
  "key": "C",
  "tempo": 140,
  "section": "whole song",
  "start": 0,
  "dur": 20,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-IV-V, the oldest loop there is. The bass outlines it: C, F, G.",
  "spotify": "spotify:track:4HK4uzQypFwpimY5FfcoPV",
  "art": "https://i.scdn.co/image/ab67616d00001e0212dafc73ddff160e2a9e8b14",
  "ug": "https://tabs.ultimate-guitar.com/tab/ritchie-valens/la-bamba-official-2548152"
 },
 {
  "id": "wild-thing-the-troggs",
  "title": "Wild Thing",
  "artist": "The Troggs",
  "year": 1966,
  "key": "A",
  "tempo": 104,
  "section": "verse",
  "start": 0,
  "dur": 20,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "I-IV-V-IV. Notice the V does not go home; it steps back to IV first.",
  "spotify": "spotify:track:7jGzYUZ2Bgg8BDfYlQRfn8",
  "art": "https://i.scdn.co/image/ab67616d00001e0227b24620f0b3b592472552f5",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-troggs/wild-thing-official-2140775"
 },
 {
  "id": "bad-moon-rising-creedence-clearwater-revival",
  "title": "Bad Moon Rising",
  "artist": "Creedence Clearwater Revival",
  "year": 1969,
  "key": "D",
  "tempo": 90,
  "section": "verse",
  "start": 0,
  "dur": 18,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "I, then a quick V-IV, then home. The V-IV pair goes down a step in the bass: A to G.",
  "spotify": "spotify:track:20OFwXhEXf12DzwXmaV7fj",
  "art": "https://i.scdn.co/image/ab67616d00001e023efcd243aaa5638f55318f91",
  "ug": "https://tabs.ultimate-guitar.com/tab/creedence-clearwater-revival/bad-moon-rising-official-1947475"
 },
 {
  "id": "dancing-on-my-own-robyn",
  "title": "Dancing On My Own",
  "artist": "Robyn",
  "year": 2010,
  "key": "Gb",
  "tempo": 118,
  "section": "verse",
  "start": 0,
  "dur": 24,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-IV under a synth pulse. Same three chords as Chasing Cars, on a dance floor.",
  "spotify": "spotify:track:3Rc2ajBMInxeNGVkMPC92Y",
  "art": "https://i.scdn.co/image/ab67616d00001e0214e2eafece9d75406a591978",
  "ug": "https://tabs.ultimate-guitar.com/tab/robyn/dancing-on-my-own-official-2592132"
 },
 {
  "id": "stand-by-me-ben-e-king",
  "title": "Stand By Me",
  "artist": "Ben E. King",
  "year": 1962,
  "key": "A",
  "tempo": 118,
  "section": "whole song",
  "start": 0,
  "dur": 26,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "vi",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "The '50s progression: I-vi-IV-V. The bass line IS the hook, so the roots are handed to you.",
  "spotify": "spotify:track:3SdTKo2uVsxFblQjpScoHy",
  "art": "https://i.scdn.co/image/ab67616d00001e021813ea8f590a0aab2820f922",
  "ug": "https://tabs.ultimate-guitar.com/tab/ben-e-king/stand-by-me-official-2077939"
 },
 {
  "id": "every-breath-you-take-the-police",
  "title": "Every Breath You Take",
  "artist": "The Police",
  "year": 1983,
  "key": "Ab",
  "tempo": 117,
  "section": "verse",
  "start": 0,
  "dur": 22,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "Same I-vi-IV-V as Stand By Me, played as arpeggios. Hear the drop from I down to vi.",
  "spotify": "spotify:track:1JSTJqkT5qHq8MDJnJbRE1",
  "art": "https://i.scdn.co/image/ab67616d00001e02c8e97cafeb2acb85b21a777e",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-police/every-breath-you-take-official-1910907"
 },
 {
  "id": "with-or-without-you-u2",
  "title": "With or Without You",
  "artist": "U2",
  "year": 2006,
  "key": "D",
  "tempo": 110,
  "section": "intro / verse",
  "start": 0,
  "dur": 28,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-vi-IV: the most-used loop in pop. The bass plays only roots, one per bar: D, A, B, G.",
  "spotify": "spotify:track:6QPhpvO1pWDS91EsEmzsbc",
  "art": "https://i.scdn.co/image/ab67616d00001e020378fba8fe57b59a6244bb62",
  "ug": "https://tabs.ultimate-guitar.com/tab/u2/with-or-without-you-official-1955543"
 },
 {
  "id": "don-t-stop-believin-journey",
  "title": "Don't Stop Believin'",
  "artist": "Journey",
  "year": 2001,
  "key": "E",
  "tempo": 119,
  "section": "intro (first 4 bars)",
  "start": 0,
  "dur": 8,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-vi-IV for the first four bars; the second four swap vi for iii (G#m). Compare with U2: same numerals, different key and feel.",
  "spotify": "spotify:track:77NNZQSqzLNqh2A9JhLRkg",
  "art": "https://i.scdn.co/image/ab67616d00001e020f6ce5c138493ac768d9afc8",
  "ug": "https://tabs.ultimate-guitar.com/tab/journey/dont-stop-believin-official-2052817"
 },
 {
  "id": "i-m-yours-jason-mraz",
  "title": "I'm Yours",
  "artist": "Jason Mraz",
  "year": 2008,
  "key": "B",
  "tempo": 76,
  "section": "intro / verse",
  "start": 0,
  "dur": 26,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-vi-IV once more. By now the drop from V to vi should sound like a familiar sigh.",
  "spotify": "spotify:track:1EzrEOXmMH3G43AXT1y7pA",
  "art": "https://i.scdn.co/image/ab67616d00001e02125b1a330b6f6100ab19dbed",
  "ug": "https://tabs.ultimate-guitar.com/tab/jason-mraz/im-yours-official-1910841"
 },
 {
  "id": "take-me-home-country-roads-john-denver",
  "title": "Take Me Home, Country Roads",
  "artist": "John Denver",
  "year": 1997,
  "key": "A",
  "tempo": 82,
  "section": "verse",
  "start": 8,
  "dur": 24,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-vi-V-IV. The vi comes second here, not third; the V-IV at the end steps down a whole tone.",
  "spotify": "spotify:track:1QbOvACeYanja5pbnJbAmk",
  "art": "https://i.scdn.co/image/ab67616d00001e02a19cee952b6dae128d68f116",
  "ug": "https://tabs.ultimate-guitar.com/tab/john-denver/take-me-home-country-roads-official-2401639"
 },
 {
  "id": "free-fallin-tom-petty",
  "title": "Free Fallin'",
  "artist": "Tom Petty",
  "year": 1989,
  "key": "F",
  "tempo": 84,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "I-IV-I-V in quick two-beat changes. The top strings barely move; the bass tells the story.",
  "spotify": "spotify:track:5tVA6TkbaAH9QMITTQRrNv",
  "art": "https://i.scdn.co/image/ab67616d00001e0236572e6726714544f5bed456",
  "ug": "https://tabs.ultimate-guitar.com/tab/tom-petty/free-fallin-official-2172543"
 },
 {
  "id": "riptide-vance-joy",
  "title": "Riptide",
  "artist": "Vance Joy",
  "year": 2014,
  "key": "Db",
  "tempo": 100,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 2,
  "chords": [
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "Starts on vi, not I. vi-V-I: minor, then a step down, then home for two bars. (The official chart calls the key Bb minor, which makes it i-VII-III; same chords, different home.)",
  "spotify": "spotify:track:7yq4Qj7cqayVTp3FF9CWbm",
  "art": "https://i.scdn.co/image/ab67616d00001e02d3ce97395ff522b0d70c1094",
  "ug": "https://tabs.ultimate-guitar.com/tab/vance-joy/riptide-official-2104813"
 },
 {
  "id": "fast-car-tracy-chapman",
  "title": "Fast Car",
  "artist": "Tracy Chapman",
  "year": 1988,
  "key": "A",
  "tempo": 104,
  "section": "intro riff",
  "start": 0,
  "dur": 26,
  "level": 2,
  "chords": [
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "std",
  "note": "The riff starts on IV, so home arrives on the second chord. IV-I-vi-V.",
  "spotify": "spotify:track:2M9ro2krNb7nr7HSprkEgo",
  "art": "https://i.scdn.co/image/ab67616d00001e0290b8a540137ee2a718a369f9",
  "ug": "https://tabs.ultimate-guitar.com/tab/tracy-chapman/fast-car-official-1962589"
 },
 {
  "id": "viva-la-vida-coldplay",
  "title": "Viva La Vida",
  "artist": "Coldplay",
  "year": 2008,
  "key": "Ab",
  "tempo": 138,
  "section": "intro",
  "start": 0,
  "dur": 24,
  "level": 2,
  "chords": [
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "IV-V-I-vi. The strings start away from home and land on I on the third chord.",
  "spotify": "spotify:track:1mea3bSkSGXuIRvnydlB5b",
  "art": "https://i.scdn.co/image/ab67616d00001e02e21cc1db05580b6f2d2a3b6e",
  "ug": "https://tabs.ultimate-guitar.com/tab/coldplay/viva-la-vida-official-1910847"
 },
 {
  "id": "the-scientist-coldplay",
  "title": "The Scientist",
  "artist": "Coldplay",
  "year": 2002,
  "key": "F",
  "tempo": 74,
  "section": "intro / verse",
  "start": 0,
  "dur": 26,
  "level": 2,
  "chords": [
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "vi-IV-I-I on piano. Two bars of I at the end let the loop breathe.",
  "spotify": "spotify:track:75JFxkI2RXiU7L9VXzMkle",
  "art": "https://i.scdn.co/image/ab67616d00001e02de09e02aa7febf30b7c02d82",
  "ug": "https://tabs.ultimate-guitar.com/tab/coldplay/the-scientist-official-2090785"
 },
 {
  "id": "yellow-coldplay",
  "title": "Yellow",
  "artist": "Coldplay",
  "year": 2000,
  "key": "B",
  "tempo": 86,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "V",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "I-V-IV, two bars each. The guitar strums the same shape up the neck; the bass gives it away.",
  "spotify": "spotify:track:3AJwUDP919kvQ9QcozQPxg",
  "art": "https://i.scdn.co/image/ab67616d00001e029164bafe9aaa168d93f4816a",
  "ug": "https://tabs.ultimate-guitar.com/tab/coldplay/yellow-official-1940647"
 },
 {
  "id": "just-like-heaven-the-cure",
  "title": "Just Like Heaven",
  "artist": "The Cure",
  "year": 1987,
  "key": "A",
  "tempo": 150,
  "section": "intro",
  "start": 0,
  "dur": 20,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "ii",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-ii-IV. The ii is the surprise: a minor chord where you might expect vi. Compare them on the band.",
  "spotify": "spotify:track:76GlO5H5RT6g7y0gev86Nk",
  "art": "https://i.scdn.co/image/ab67616d00001e027f22337546d61faca55e0f4f",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-cure/just-like-heaven-official-1961213"
 },
 {
  "id": "beast-of-burden-the-rolling-stones",
  "title": "Beast of Burden",
  "artist": "The Rolling Stones",
  "year": 1978,
  "key": "E",
  "tempo": 100,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2,
    "bass": "3"
   },
   {
    "rn": "vi",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "I-V/3-vi-IV in two-beat changes. The B sits on D#, so the bass walks E, D#, C# and then drops to A: the four-chord loop with a walking bass.",
  "spotify": "spotify:track:77oU2rjC5XbjQfNe3bD6so",
  "art": "https://i.scdn.co/image/ab67616d00001e0205c7aec05eabf142cc33b936",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-rolling-stones/beast-of-burden-official-2459440"
 },
 {
  "id": "dead-flowers-the-rolling-stones",
  "title": "Dead Flowers",
  "artist": "The Rolling Stones",
  "year": 1971,
  "key": "D",
  "tempo": 130,
  "section": "verse",
  "start": 0,
  "dur": 20,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-IV-I: country rock. The V-IV step down in the bass is the Stones' favourite move.",
  "spotify": "spotify:track:3oJtUnnt5uYPtzulIbLw3D",
  "art": "https://i.scdn.co/image/ab67616d00001e02a1d9c9969f2a7ed27e449a3c",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-rolling-stones/dead-flowers-official-2659710"
 },
 {
  "id": "a-real-hero-college",
  "title": "A Real Hero",
  "artist": "College",
  "year": 2010,
  "key": "F",
  "tempo": 100,
  "section": "intro",
  "start": 0,
  "dur": 26,
  "level": 2,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-vi-IV-V on soft synths (the Drive song): the '50s progression at synthwave tempo.",
  "spotify": "spotify:track:1aJrVsHwcQMZ8TZ6mlvT5J",
  "art": "https://i.scdn.co/image/ab67616d00001e0216fd333484d62242764455f0",
  "ug": "https://tabs.ultimate-guitar.com/tab/college/a-real-hero-official-2150855"
 },
 {
  "id": "wake-me-up-avicii",
  "title": "Wake Me Up",
  "artist": "Avicii",
  "year": 2013,
  "key": "D",
  "tempo": 124,
  "section": "intro guitar",
  "start": 0,
  "dur": 24,
  "level": 4,
  "chords": [
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IVmaj7",
    "beats": 4,
    "bass": "5"
   },
   {
    "rn": "I",
    "beats": 4,
    "bass": "5"
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "vi, IV over its fifth, I over its fifth, V. The chords are the 'sad but uplifting' loop, but the bass sits on D and A under the middle two, so it barely moves.",
  "spotify": "spotify:track:0nrRP2bk19rLc0orkWPQk2",
  "art": "https://i.scdn.co/image/ab67616d00001e02e14f11f796cef9f9a82691a7",
  "ug": "https://tabs.ultimate-guitar.com/tab/avicii/wake-me-up-official-1997319"
 },
 {
  "id": "all-along-the-watchtower-jimi-hendrix",
  "title": "All Along the Watchtower",
  "artist": "Jimi Hendrix",
  "year": 1968,
  "key": "C minor",
  "tempo": 112,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 2
   },
   {
    "rn": "VII",
    "beats": 2
   },
   {
    "rn": "VI",
    "beats": 2
   },
   {
    "rn": "VII",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "i-VII-VI-VII. The bass walks down two steps and back: C, Bb, Ab, Bb. Hendrix tunes down a half step, so it sounds in C minor.",
  "spotify": "spotify:track:2aoo2jlRnM3A0NyLQqMN2f",
  "art": "https://i.scdn.co/image/ab67616d00001e02522088789d49e216d9818292",
  "ug": "https://tabs.ultimate-guitar.com/tab/jimi-hendrix/all-along-the-watchtower-official-1938005"
 },
 {
  "id": "sultans-of-swing-dire-straits",
  "title": "Sultans of Swing",
  "artist": "Dire Straits",
  "year": 1978,
  "key": "D minor",
  "tempo": 148,
  "section": "verse",
  "start": 20,
  "dur": 22,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-VII-VI-V: the bass falls a step at a time, D, C, Bb, A, then the V pulls back up to i.",
  "spotify": "spotify:track:6cr6UDpkjEaMQ80OjWqEBQ",
  "art": "https://i.scdn.co/image/ab67616d00001e0205b07080bdc2dd0e2cf6f008",
  "ug": "https://tabs.ultimate-guitar.com/tab/dire-straits/sultans-of-swing-official-1911505"
 },
 {
  "id": "ain-t-no-sunshine-bill-withers",
  "title": "Ain't No Sunshine",
  "artist": "Bill Withers",
  "year": 1971,
  "key": "A minor",
  "tempo": 78,
  "section": "verse",
  "start": 0,
  "dur": 20,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 2
   },
   {
    "rn": "VII",
    "beats": 2
   },
   {
    "rn": "i",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i, then a quick v-VII, then home. The v is minor here (Em), which keeps it dark.",
  "spotify": "spotify:track:1k1Bqnv2R0uJXQN4u6LKYt",
  "art": "https://i.scdn.co/image/ab67616d00001e02f64b9ea8a8a409c6af86134f",
  "ug": "https://tabs.ultimate-guitar.com/tab/bill-withers/aint-no-sunshine-official-2075151"
 },
 {
  "id": "losing-my-religion-r-e-m",
  "title": "Losing My Religion",
  "artist": "R.E.M.",
  "year": 1991,
  "key": "A minor",
  "tempo": 126,
  "section": "verse",
  "start": 12,
  "dur": 22,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 4
   },
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 4
   },
   {
    "rn": "iv",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-v-i-v then iv-VII. The mandolin hides the changes; the bass does not.",
  "spotify": "spotify:track:31AOj9sFz2gM0O3hMARRBx",
  "art": "https://i.scdn.co/image/ab67616d00001e02e2dd4e821bcc3f70dc0c8ffd",
  "ug": "https://tabs.ultimate-guitar.com/tab/r-e-m-/losing-my-religion-official-1916647"
 },
 {
  "id": "boulevard-of-broken-dreams-green-day",
  "title": "Boulevard of Broken Dreams",
  "artist": "Green Day",
  "year": 2017,
  "key": "F minor",
  "tempo": 84,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-III-VII-IV. That last IV is major (Bb over F minor): the Dorian sound. Compare with iv on the band.",
  "spotify": "spotify:track:5GorCbAP4aL0EJ16frG2hd",
  "art": "https://i.scdn.co/image/ab67616d00001e027f213369d5265a60af5f7e82",
  "ug": "https://tabs.ultimate-guitar.com/tab/green-day/boulevard-of-broken-dreams-official-1910951"
 },
 {
  "id": "mad-world-gary-jules",
  "title": "Mad World",
  "artist": "Gary Jules",
  "year": 2001,
  "key": "F minor",
  "tempo": 88,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "Exactly the same i-III-VII-IV as Boulevard of Broken Dreams, on a piano. Same numerals, same feel.",
  "spotify": "spotify:track:3JOVTQ5h8HGFnDdp4VT3MP",
  "art": "https://i.scdn.co/image/ab67616d00001e027948eec521c67e76cafe30a0",
  "ug": "https://tabs.ultimate-guitar.com/tab/gary-jules/mad-world-official-2148405"
 },
 {
  "id": "hurt-johnny-cash",
  "title": "Hurt",
  "artist": "Johnny Cash",
  "year": 2002,
  "key": "A minor",
  "tempo": 76,
  "section": "intro / verse",
  "start": 0,
  "dur": 22,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "i-III-IV, a Dorian loop. The major IV (D) is the chord that makes it ache rather than mope.",
  "spotify": "spotify:track:28cnXtME493VX9NOw9cIUh",
  "art": "https://i.scdn.co/image/ab67616d00001e026f4f62da3d811b6501a69ffa",
  "ug": "https://tabs.ultimate-guitar.com/tab/johnny-cash/hurt-official-1948797"
 },
 {
  "id": "smells-like-teen-spirit-nirvana",
  "title": "Smells Like Teen Spirit",
  "artist": "Nirvana",
  "year": 1991,
  "key": "F minor",
  "tempo": 117,
  "section": "intro riff",
  "start": 0,
  "dur": 16,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 2
   },
   {
    "rn": "iv",
    "beats": 2
   },
   {
    "rn": "III",
    "beats": 2
   },
   {
    "rn": "VI",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "Power chords, so no thirds: i-iv-III-VI. Hear it as two pairs: up a fourth, then up a fourth again.",
  "spotify": "spotify:track:5ghIJDpPoe3CfHMGu71E6T",
  "art": "https://i.scdn.co/image/ab67616d00001e02e175a19e530c898d167d39bf",
  "ug": "https://tabs.ultimate-guitar.com/tab/nirvana/smells-like-teen-spirit-official-1910941"
 },
 {
  "id": "crazy-gnarls-barkley",
  "title": "Crazy",
  "artist": "Gnarls Barkley",
  "year": 2006,
  "key": "C minor",
  "tempo": 112,
  "section": "intro / verse",
  "start": 0,
  "dur": 18,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 8
   },
   {
    "rn": "III",
    "beats": 8
   },
   {
    "rn": "VI",
    "beats": 8
   },
   {
    "rn": "V",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "i-III-VI-V, two bars each. The V (G major) at the end is the classic minor-key turnaround.",
  "spotify": "spotify:track:6o1l9I0faXJN2iqulHrdCQ",
  "art": "https://i.scdn.co/image/ab67616d00001e02ab051a2c680f39c0d9827706",
  "ug": "https://tabs.ultimate-guitar.com/tab/gnarls-barkley/crazy-official-2189997"
 },
 {
  "id": "get-lucky-daft-punk",
  "title": "Get Lucky",
  "artist": "Daft Punk",
  "year": 2013,
  "key": "B minor",
  "tempo": 116,
  "section": "whole song",
  "start": 0,
  "dur": 24,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "One loop all night: i-III-v-IV. The major IV (E) over B minor is Dorian, the disco-funk colour.",
  "spotify": "spotify:track:69kOkLUCkxIZYexIgSG8rq",
  "art": "https://i.scdn.co/image/ab67616d00001e029b9b36b0e22870b9f542d937",
  "ug": "https://tabs.ultimate-guitar.com/tab/daft-punk/get-lucky-official-1911501"
 },
 {
  "id": "bad-guy-billie-eilish",
  "title": "bad guy",
  "artist": "Billie Eilish",
  "year": 2021,
  "key": "G minor",
  "tempo": 135,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 8
   },
   {
    "rn": "iv",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-iv-V on a bass synth. Almost nothing but the bass, which is the point.",
  "spotify": "spotify:track:1hewNsVmijBqjKvFRQfk4m",
  "art": "https://i.scdn.co/image/ab67616d00001e02ea43df0e1b41371713ac2f7d",
  "ug": "https://tabs.ultimate-guitar.com/tab/billie-eilish/bad-guy-official-2650386"
 },
 {
  "id": "sweet-dreams-are-made-of-this-eurythmics",
  "title": "Sweet Dreams (Are Made of This)",
  "artist": "Eurythmics",
  "year": 1991,
  "key": "C minor",
  "tempo": 125,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 8
   },
   {
    "rn": "VI",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-VI-V. The synth bass riff outlines C minor; then Ab and G come down to it.",
  "spotify": "spotify:track:6zIfdCmmhPCX0cMquBsC37",
  "art": "https://i.scdn.co/image/ab67616d00001e02b63cf86e40fa66f81c6fc8d5",
  "ug": "https://tabs.ultimate-guitar.com/tab/eurythmics/sweet-dreams-are-made-of-this-official-2003341"
 },
 {
  "id": "house-of-the-rising-sun-the-animals",
  "title": "House of the Rising Sun",
  "artist": "The Animals",
  "year": 1964,
  "key": "A minor",
  "tempo": 80,
  "section": "intro / verse",
  "start": 0,
  "dur": 22,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 3
   },
   {
    "rn": "III",
    "beats": 3
   },
   {
    "rn": "IV",
    "beats": 3
   },
   {
    "rn": "VI",
    "beats": 3
   },
   {
    "rn": "i",
    "beats": 3
   },
   {
    "rn": "III",
    "beats": 3
   },
   {
    "rn": "V",
    "beats": 6
   }
  ],
  "src": "official",
  "note": "In 6/8, arpeggiated: i-III-IV-VI, i-III-V. The bass climbs A, C, D, F.",
  "spotify": "spotify:track:7BY005dacJkbO6EPiOh2wb",
  "art": "https://i.scdn.co/image/ab67616d00001e023c534611bd3658006378a2d7",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-animals/house-of-the-rising-sun-official-1944405"
 },
 {
  "id": "levels-avicii",
  "title": "Levels",
  "artist": "Avicii",
  "year": 2011,
  "key": "C# minor",
  "tempo": 126,
  "section": "intro / hook",
  "start": 0,
  "dur": 24,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-III-VII-VI: the big-room EDM loop. Starts minor, ends on VI, which makes the return to i feel like a lift.",
  "spotify": "spotify:track:5UqCQaDshqbIk3pkhy4Pjg",
  "art": "https://i.scdn.co/image/ab67616d00001e02ffb343926530168be4724dd4",
  "ug": "https://tabs.ultimate-guitar.com/tab/avicii/levels-official-3727517"
 },
 {
  "id": "thinking-out-loud-ed-sheeran",
  "title": "Thinking Out Loud",
  "artist": "Ed Sheeran",
  "year": 2014,
  "key": "D",
  "tempo": 79,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 2,
    "bass": "3"
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "I, I/3, IV, V. The chord does not change between the first two, only the bass climbs D to F#. Toggle 'bass on roots' to hear the difference.",
  "spotify": "spotify:track:34gCuhDGsG4bRPIf9bb02f",
  "art": "https://i.scdn.co/image/ab67616d00001e0213b3e37318a0c247b550bccd",
  "ug": "https://tabs.ultimate-guitar.com/tab/ed-sheeran/thinking-out-loud-official-1954983"
 },
 {
  "id": "wonderful-tonight-eric-clapton",
  "title": "Wonderful Tonight",
  "artist": "Eric Clapton",
  "year": 1977,
  "key": "G",
  "tempo": 96,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I, V/3, IV, V. The bass walks down G, F#, then jumps to C. The second and fourth chords are the same D; only the bass differs.",
  "spotify": "spotify:track:6zC0mpGYwbNTpk9SKwh08f",
  "art": "https://i.scdn.co/image/ab67616d00001e026f093a6ae88a5ca8ed53b9f7",
  "ug": "https://tabs.ultimate-guitar.com/tab/eric-clapton/wonderful-tonight-official-1910971"
 },
 {
  "id": "landslide-fleetwood-mac",
  "title": "Landslide",
  "artist": "Fleetwood Mac",
  "year": 1975,
  "key": "Eb",
  "tempo": 80,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4,
    "bass": "3"
   }
  ],
  "src": "official",
  "note": "I, V/3, vi, V/3. The bass steps down Eb, D, C, D: a scale fragment. The V never sits on its root.",
  "spotify": "spotify:track:5ihS6UUlyQAfmp48eSkxuQ",
  "art": "https://i.scdn.co/image/ab67616d00001e024fb043195e8d07e72edc7226",
  "ug": "https://tabs.ultimate-guitar.com/tab/fleetwood-mac/landslide-official-2158823"
 },
 {
  "id": "someone-like-you-adele",
  "title": "Someone Like You",
  "artist": "Adele",
  "year": 2011,
  "key": "A",
  "tempo": 68,
  "section": "intro / verse",
  "start": 0,
  "dur": 26,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "iii",
    "beats": 4,
    "bass": "5"
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I, iii/5, vi, IV. The bass descends A, G#, F#, then D. The G# bass under C#m makes the iii sound like a passing chord.",
  "spotify": "spotify:track:1zwMYTA5nlNjZxYrvBB2pV",
  "art": "https://i.scdn.co/image/ab67616d00001e027e7e5dd9d1ab19fcded8a17f",
  "ug": "https://tabs.ultimate-guitar.com/tab/adele/someone-like-you-official-2093941"
 },
 {
  "id": "kids-mgmt",
  "title": "Kids",
  "artist": "MGMT",
  "year": 2007,
  "key": "F# minor",
  "tempo": 123,
  "section": "intro synth",
  "start": 0,
  "dur": 24,
  "level": 4,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4,
    "bass": "3"
   }
  ],
  "src": "official",
  "note": "i-VI-III-VII/3 in F# minor (or vi-IV-I-V/3 if you hear it in A). The E sits on its third, G#, so the bass walks F#, D, A, G# and back to F#.",
  "spotify": "spotify:track:1jJci4qxiYcOHhQR247rEU",
  "art": "https://i.scdn.co/image/ab67616d00001e02abdf7749aeb5229dbf305f03",
  "ug": "https://tabs.ultimate-guitar.com/tab/mgmt/kids-official-2007423"
 },
 {
  "id": "high-and-dry-radiohead",
  "title": "High and Dry",
  "artist": "Radiohead",
  "year": 1995,
  "key": "E",
  "tempo": 88,
  "section": "intro / verse",
  "start": 5,
  "dur": 24,
  "level": 2,
  "chords": [
   {
    "rn": "ii7",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "ii-IV-I. The official chart writes the first chord as Asus2 over F#, which is F#m7 by another name: a minor chord that lifts to IV and settles on I.",
  "spotify": "spotify:track:2a1iMaoWQ5MnvLFBDv4qkf",
  "art": "https://i.scdn.co/image/ab67616d00001e029293c743fa542094336c5e12",
  "ug": "https://tabs.ultimate-guitar.com/tab/radiohead/high-and-dry-official-1942949"
 },
 {
  "id": "nightcall-kavinsky",
  "title": "Nightcall",
  "artist": "Kavinsky",
  "year": 2010,
  "key": "A minor",
  "tempo": 90,
  "section": "intro / verse",
  "start": 0,
  "dur": 26,
  "level": 3,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 4
   },
   {
    "rn": "iv",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-VII-VI-iv. A natural-minor descent, A, G, F, then D; the iv at the end keeps it dark instead of resolving.",
  "spotify": "spotify:track:0U0ldCRmgCqhVvD6ksG63j",
  "art": "https://i.scdn.co/image/ab67616d00001e02d6d8c2eaa1f9031b62f7a3f7",
  "ug": "https://tabs.ultimate-guitar.com/tab/kavinsky/nightcall-official-1967119"
 },
 {
  "id": "zombie-the-cranberries",
  "title": "Zombie",
  "artist": "The Cranberries",
  "year": 2008,
  "key": "E minor",
  "tempo": 84,
  "section": "intro / verse",
  "start": 0,
  "dur": 22,
  "level": 4,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4,
    "bass": "3"
   }
  ],
  "src": "official",
  "note": "i-VI-III-VII/3. The last chord is D over F#, so the bass ends a half step above E and leans back into it.",
  "spotify": "spotify:track:49wOjOkS4pBK3PQnPnNYjb",
  "art": "https://i.scdn.co/image/ab67616d00001e02d6e06307a0b89eb7586716e7",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-cranberries/zombie-official-1918857"
 },
 {
  "id": "tiny-dancer-elton-john",
  "title": "Tiny Dancer",
  "artist": "Elton John",
  "year": 1971,
  "key": "C",
  "tempo": 72,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 1,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "C to F and back on the piano, slowly. The right hand changes more than the left; listen for the bass moving up a fourth.",
  "spotify": "spotify:track:2TVxnKdb3tqe1nhQWwwZCO",
  "art": "https://i.scdn.co/image/ab67616d00001e02d03ab2da904d8251a87bbc31",
  "ug": "https://tabs.ultimate-guitar.com/tab/elton-john/tiny-dancer-official-2598090"
 },
 {
  "id": "your-song-elton-john",
  "title": "Your Song",
  "artist": "Elton John",
  "year": 1970,
  "key": "Eb",
  "tempo": 66,
  "section": "verse",
  "start": 14,
  "dur": 22,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "IVmaj7",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "iii",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I, IVmaj7, V over its third, iii. The bass walks Eb, Ab, D, G: the V sits on D so the line can step down into the G minor.",
  "spotify": "spotify:track:38zsOOcu31XbbYj9BIPUF1",
  "art": "https://i.scdn.co/image/ab67616d00001e024b292ed7c7360a04d3d6b74a",
  "ug": "https://tabs.ultimate-guitar.com/tab/elton-john/your-song-official-2163551"
 },
 {
  "id": "babe-i-m-gonna-leave-you-led-zeppelin",
  "title": "Babe I'm Gonna Leave You",
  "artist": "Led Zeppelin",
  "year": 1969,
  "key": "A minor",
  "tempo": 68,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 4,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "VI",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "A descending bass: A, G, F#, F, E. The chords are i, VII, IV/3, VI, V; the D over F# exists only to keep the bass stepping down.",
  "spotify": "spotify:track:4OMu5a8sFpcRCPCcsoEaov",
  "art": "https://i.scdn.co/image/ab67616d00001e026f2f499c1df1f210c9b34b32",
  "ug": "https://tabs.ultimate-guitar.com/tab/led-zeppelin/babe-im-gonna-leave-you-official-2450563"
 },
 {
  "id": "sweet-home-alabama-lynyrd-skynyrd",
  "title": "Sweet Home Alabama",
  "artist": "Lynyrd Skynyrd",
  "year": 1974,
  "key": "D",
  "tempo": 98,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "bVII",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-bVII-IV: the Mixolydian rock loop. bVII (C) is not in D major; it is borrowed from the key of D's parent, G. Some hear this in G as V-IV-I.",
  "spotify": "spotify:track:7e89621JPkKaeDSTQ3avtg",
  "art": "https://i.scdn.co/image/ab67616d00001e0217e1907923e91181f38290ac",
  "ug": "https://tabs.ultimate-guitar.com/tab/lynyrd-skynyrd/sweet-home-alabama-official-1916259"
 },
 {
  "id": "gimme-shelter-the-rolling-stones",
  "title": "Gimme Shelter",
  "artist": "The Rolling Stones",
  "year": 1969,
  "key": "C#",
  "tempo": 118,
  "section": "intro",
  "start": 0,
  "dur": 26,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "bVII",
    "beats": 2
   },
   {
    "rn": "bVI",
    "beats": 2
   },
   {
    "rn": "bVII",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "I-bVII-bVI-bVII. Two borrowed chords, each a whole step down, then back up. Hear the bass fall C#, B, A and climb back to B.",
  "spotify": "spotify:track:6H3kDe7CGoWYBabAeVWGiD",
  "art": "https://i.scdn.co/image/ab67616d00001e022af30c881bb23cfb82a8cf99",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-rolling-stones/gimme-shelter-official-2421543"
 },
 {
  "id": "whole-lotta-love-led-zeppelin",
  "title": "Whole Lotta Love",
  "artist": "Led Zeppelin",
  "year": 1969,
  "key": "E",
  "tempo": 90,
  "section": "intro riff",
  "start": 0,
  "dur": 18,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "bVII",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "I-bVII, riff-style. The D against E major is the blues-rock 'flat seven' sound.",
  "spotify": "spotify:track:0hCB0YR03f6AmQaHbwWDe8",
  "art": "https://i.scdn.co/image/ab67616d00001e02fc4f17340773c6c3579fea0d",
  "ug": "https://tabs.ultimate-guitar.com/tab/led-zeppelin/whole-lotta-love-official-1931003"
 },
 {
  "id": "hey-joe-jimi-hendrix",
  "title": "Hey Joe",
  "artist": "Jimi Hendrix",
  "year": 1967,
  "key": "E",
  "tempo": 82,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 5,
  "chords": [
   {
    "rn": "bVI",
    "beats": 2
   },
   {
    "rn": "bIII",
    "beats": 2
   },
   {
    "rn": "bVII",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "bVI-bIII-bVII-IV-I: a chain of rising fifths (C, G, D, A, E). Only the last two are in the key of E.",
  "spotify": "spotify:track:0NWPxcsf5vdjdiFUI8NgkP",
  "art": "https://i.scdn.co/image/ab67616d00001e02c9adfbd773852e286faed040",
  "ug": "https://tabs.ultimate-guitar.com/tab/jimi-hendrix/hey-joe-official-1934101"
 },
 {
  "id": "creep-radiohead",
  "title": "Creep",
  "artist": "Radiohead",
  "year": 1993,
  "key": "G",
  "tempo": 92,
  "section": "intro / verse",
  "start": 0,
  "dur": 21,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 8
   },
   {
    "rn": "III",
    "beats": 8
   },
   {
    "rn": "IV",
    "beats": 8
   },
   {
    "rn": "iv",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "I-III-IV-iv. The III (B major) is a surprise, and the IV turning minor at the end is the Creep chord.",
  "spotify": "spotify:track:70LcF31zb1H0PyJoS1Sx1r",
  "art": "https://i.scdn.co/image/ab67616d00001e02ec548c00d3ac2f10be73366d",
  "ug": "https://tabs.ultimate-guitar.com/tab/radiohead/creep-official-1911339"
 },
 {
  "id": "santeria-sublime",
  "title": "Santeria",
  "artist": "Sublime",
  "year": 1996,
  "key": "E",
  "tempo": 92,
  "section": "intro / verse",
  "start": 0,
  "dur": 22,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-III-vi-V. Like Creep, the III (G# major) is the odd one out: it pulls hard toward vi.",
  "spotify": "spotify:track:2hnMS47jN0etwvFPzYk11f",
  "art": "https://i.scdn.co/image/ab67616d00001e028fc4b0dcfb9509553f195c85",
  "ug": "https://tabs.ultimate-guitar.com/tab/sublime/santeria-official-1960777"
 },
 {
  "id": "where-is-my-mind-pixies",
  "title": "Where Is My Mind?",
  "artist": "Pixies",
  "year": 1997,
  "key": "E",
  "tempo": 80,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-vi-III-IV. The G# major (III) after C#m is what makes the ooh-ooh section feel like it tilts.",
  "spotify": "spotify:track:0KzAbK6nItSqNh8q70tb0K",
  "art": "https://i.scdn.co/image/ab67616d00001e02aa13b5cb5c07db8c508b96db",
  "ug": "https://tabs.ultimate-guitar.com/tab/pixies/where-is-my-mind-official-1941517"
 },
 {
  "id": "hey-ya-outkast",
  "title": "Hey Ya!",
  "artist": "OutKast",
  "year": 2003,
  "key": "G",
  "tempo": 79,
  "section": "intro / verse",
  "start": 0,
  "dur": 20,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 8
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "I-IV-V-VI. That final E major is not in G at all. It is the brightest chord in the song.",
  "spotify": "spotify:track:2PpruBYCo4H7WOBJ7Q2EwM",
  "art": "https://i.scdn.co/image/ab67616d00001e026e88eb6508fd94cd1b745ce2",
  "ug": "https://tabs.ultimate-guitar.com/tab/outkast/hey-ya-official-2210659"
 },
 {
  "id": "wonderwall-oasis",
  "title": "Wonderwall",
  "artist": "Oasis",
  "year": 1995,
  "key": "A",
  "tempo": 87,
  "section": "intro / verse",
  "start": 0,
  "dur": 22,
  "level": 5,
  "chords": [
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "II",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "vi-I-V-II. The II (B7sus4) is a major chord on the second degree, borrowed from E major.",
  "spotify": "spotify:track:1qPbGZqppFwLwcBC1JQ6Vr",
  "art": "https://i.scdn.co/image/ab67616d00001e022f2eeee9b405f4d00428d84c",
  "ug": "https://tabs.ultimate-guitar.com/tab/oasis/wonderwall-official-1910851"
 },
 {
  "id": "don-t-look-back-in-anger-oasis",
  "title": "Don't Look Back in Anger",
  "artist": "Oasis",
  "year": 1995,
  "key": "C",
  "tempo": 80,
  "section": "verse",
  "start": 14,
  "dur": 12,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-vi-III. The E7 (III) is a secondary dominant: it wants to go to vi, and does, next time round.",
  "spotify": "spotify:track:7ppPZa3TRUSGKaks9wH7VT",
  "art": "https://i.scdn.co/image/ab67616d00001e022f2eeee9b405f4d00428d84c",
  "ug": "https://tabs.ultimate-guitar.com/tab/oasis/dont-look-back-in-anger-official-1910905"
 },
 {
  "id": "hey-there-delilah-plain-white-t-s",
  "title": "Hey There Delilah",
  "artist": "Plain White T's",
  "year": 2005,
  "key": "D",
  "tempo": 104,
  "section": "intro / verse",
  "start": 0,
  "dur": 18,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "iii",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I to iii and back. The iii shares two notes with I, so it feels like the same chord with the bass moved up to F#.",
  "spotify": "spotify:track:4RCWB3V8V0dignt99LZ8vH",
  "art": "https://i.scdn.co/image/ab67616d00001e02beae6e69d6505fd379ef3081",
  "ug": "https://tabs.ultimate-guitar.com/tab/plain-white-ts/hey-there-delilah-official-1918965"
 },
 {
  "id": "can-t-help-falling-in-love-elvis-presley",
  "title": "Can't Help Falling in Love",
  "artist": "Elvis Presley",
  "year": 1961,
  "key": "D",
  "tempo": 96,
  "section": "verse",
  "start": 0,
  "dur": 22,
  "level": 7,
  "chords": [
   {
    "rn": "I",
    "beats": 3
   },
   {
    "rn": "iii",
    "beats": 3
   },
   {
    "rn": "vi",
    "beats": 3
   },
   {
    "rn": "vi",
    "beats": 3,
    "bass": "7"
   },
   {
    "rn": "IV",
    "beats": 3
   },
   {
    "rn": "I",
    "beats": 3
   },
   {
    "rn": "V",
    "beats": 3
   }
  ],
  "src": "official",
  "note": "In 6/8: I-iii-vi-vi/7-IV-I-V. The iii on the way to vi is the gentle, old-fashioned move, and the Bm/A keeps the bass walking down toward G.",
  "spotify": "spotify:track:44AyOl4qVkzS48vBsbNXaC",
  "art": "https://i.scdn.co/image/ab67616d00001e02b184226408f981e3dd17c606",
  "ug": "https://tabs.ultimate-guitar.com/tab/elvis-presley/cant-help-falling-in-love-official-2099065"
 },
 {
  "id": "under-the-bridge-red-hot-chili-peppers",
  "title": "Under the Bridge",
  "artist": "Red Hot Chili Peppers",
  "year": 1991,
  "key": "E",
  "tempo": 84,
  "section": "verse",
  "start": 26,
  "dur": 28,
  "level": 5,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "iii",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V-vi-iii-IV. The iii (G#m) between vi and IV is what most people miss.",
  "spotify": "spotify:track:3d9DChrdc6BOeFsbrZ3Is0",
  "art": "https://i.scdn.co/image/ab67616d00001e02153d79816d853f2694b2cc70",
  "ug": "https://tabs.ultimate-guitar.com/tab/red-hot-chili-peppers/under-the-bridge-official-1935163"
 },
 {
  "id": "teardrop-massive-attack",
  "title": "Teardrop",
  "artist": "Massive Attack",
  "year": 1998,
  "key": "A",
  "tempo": 78,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 4,
  "chords": [
   {
    "rn": "Isus4",
    "beats": 4
   },
   {
    "rn": "I7sus4",
    "beats": 4,
    "bass": "7"
   },
   {
    "rn": "IVsus2",
    "beats": 4
   },
   {
    "rn": "Isus4",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I, I over its flat seventh, IV, I. The chord barely changes for the first two bars; the bass drops A to G underneath it. Suspended voicings blur the thirds, which is the trip-hop haze.",
  "spotify": "spotify:track:67Hna13dNDkZvBpTXRIaOJ",
  "art": "https://i.scdn.co/image/ab67616d00001e022fcb0a3c7a66e516b11cd26e",
  "ug": "https://tabs.ultimate-guitar.com/tab/massive-attack/teardrop-official-2252437"
 },
 {
  "id": "mr-bojangles-nitty-gritty-dirt-band",
  "title": "Mr. Bojangles",
  "artist": "Nitty Gritty Dirt Band",
  "year": 2008,
  "key": "G",
  "tempo": 100,
  "section": "verse",
  "start": 8,
  "dur": 22,
  "level": 4,
  "chords": [
   {
    "rn": "I",
    "beats": 3
   },
   {
    "rn": "Imaj7",
    "beats": 3,
    "bass": "7"
   },
   {
    "rn": "vi7",
    "beats": 3
   },
   {
    "rn": "I",
    "beats": 3
   },
   {
    "rn": "IV",
    "beats": 3
   },
   {
    "rn": "V",
    "beats": 3
   }
  ],
  "src": "official",
  "note": "A waltz: I, Imaj7 over F#, vi7, then I-IV-V. The bass steps G, F#, E; the second chord is the same G with its seventh in the bass.",
  "spotify": "spotify:track:06uiDyZsrwnZ0o0q1Y8Ax2",
  "art": "https://i.scdn.co/image/ab67616d00001e028b80c59718e0fa200c9df90a",
  "ug": "https://tabs.ultimate-guitar.com/tab/nitty-gritty-dirt-band/mr-bojangles-official-4333247"
 },
 {
  "id": "blinding-lights-the-weeknd",
  "title": "Blinding Lights",
  "artist": "The Weeknd",
  "year": 2020,
  "key": "F minor",
  "tempo": 86,
  "section": "intro synth",
  "start": 0,
  "dur": 24,
  "level": 6,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "i-v-VII-IV. Minor v and major IV in the same loop: the '80s synth-pop Dorian blend.",
  "spotify": "spotify:track:0VjIjW4GlUZAMYd2vXMi3b",
  "art": "https://i.scdn.co/image/ab67616d00001e028863bc11d2aa12b54f5aeb36",
  "ug": "https://tabs.ultimate-guitar.com/tab/the-weeknd/blinding-lights-official-3018305"
 },
 {
  "id": "electric-feel-mgmt",
  "title": "Electric Feel",
  "artist": "MGMT",
  "year": 2007,
  "key": "C minor",
  "tempo": 104,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 7,
  "chords": [
   {
    "rn": "i",
    "beats": 2
   },
   {
    "rn": "v",
    "beats": 1
   },
   {
    "rn": "VI",
    "beats": 1
   },
   {
    "rn": "VII",
    "beats": 2
   },
   {
    "rn": "i",
    "beats": 1
   },
   {
    "rn": "v",
    "beats": 1
   },
   {
    "rn": "VI",
    "beats": 1
   }
  ],
  "src": "official",
  "note": "Cm Gm Ab, Bb Cm Gm Ab: a seven-chord loop where the second half re-enters the first. The bass jumps around; anchor on the C minor each time it comes back.",
  "spotify": "spotify:track:3FtYbEfBqAlGO46NUDQSAt",
  "art": "https://i.scdn.co/image/ab67616d00001e02abdf7749aeb5229dbf305f03",
  "ug": "https://tabs.ultimate-guitar.com/tab/mgmt/electric-feel-official-2099683"
 },
 {
  "id": "clocks-coldplay",
  "title": "Clocks",
  "artist": "Coldplay",
  "year": 2002,
  "key": "Eb",
  "tempo": 131,
  "section": "intro piano",
  "start": 0,
  "dur": 20,
  "level": 6,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 4
   },
   {
    "rn": "ii",
    "beats": 8
   }
  ],
  "src": "official",
  "note": "I-v-ii. The v is minor (Bbm) in a major key, which is why the riff never quite resolves.",
  "spotify": "spotify:track:0BCPKOYdS2jbQ8iyB56Zns",
  "art": "https://i.scdn.co/image/ab67616d00001e02de09e02aa7febf30b7c02d82",
  "ug": "https://tabs.ultimate-guitar.com/tab/coldplay/clocks-official-2093147"
 },
 {
  "id": "the-less-i-know-the-better-tame-impala",
  "title": "The Less I Know the Better",
  "artist": "Tame Impala",
  "year": 2015,
  "key": "C# minor",
  "tempo": 117,
  "section": "intro / chorus",
  "start": 0,
  "dur": 20,
  "level": 6,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "v",
    "beats": 2
   },
   {
    "rn": "VII",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "i-VII-III-v-VII in C# minor. You could hear it in E major as vi-V-I-iii-V; the bass riff decides it for C# minor.",
  "spotify": "spotify:track:6K4t31amVTZDgR3sKmwUJJ",
  "art": "https://i.scdn.co/image/ab67616d00001e029e1cfc756886ac782e363d79",
  "ug": "https://tabs.ultimate-guitar.com/tab/tame-impala/the-less-i-know-the-better-official-1949289"
 },
 {
  "id": "porcelain-moby",
  "title": "Porcelain",
  "artist": "Moby",
  "year": 2008,
  "key": "Bb",
  "tempo": 96,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 6,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "I",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "v",
    "beats": 4
   },
   {
    "rn": "ii",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I, I/3, v, ii. The bass climbs Bb to D under the same chord, then the minor v (Fm) and ii (Cm) give the loop its grey, modal wash.",
  "spotify": "spotify:track:5fJAYWoFgXm26HLNViFiUh",
  "art": "https://i.scdn.co/image/ab67616d00001e027c34c0c518ea868297cf598c",
  "ug": "https://tabs.ultimate-guitar.com/tab/moby/porcelain-official-2005309"
 },
 {
  "id": "hotel-california-eagles",
  "title": "Hotel California",
  "artist": "Eagles",
  "year": 1976,
  "key": "B minor",
  "tempo": 74,
  "section": "intro",
  "start": 0,
  "dur": 26,
  "level": 7,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "VI",
    "beats": 4
   },
   {
    "rn": "III",
    "beats": 4
   },
   {
    "rn": "iv",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "Eight bars: i-V-VII-IV-VI-III-iv-V. A descending sequence of fifths in disguise; the bass falls B, F#, A, E, G, D, then Em, F#.",
  "spotify": "spotify:track:40riOy7x9W7GXjyGp4pjAv",
  "art": "https://i.scdn.co/image/ab67616d00001e024637341b9f507521afa9a778",
  "ug": "https://tabs.ultimate-guitar.com/tab/eagles/hotel-california-official-1910943"
 },
 {
  "id": "a-whiter-shade-of-pale-procol-harum",
  "title": "A Whiter Shade of Pale",
  "artist": "Procol Harum",
  "year": 2009,
  "key": "C",
  "tempo": 74,
  "section": "intro",
  "start": 0,
  "dur": 26,
  "level": 7,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 2,
    "bass": "7"
   },
   {
    "rn": "vi7",
    "beats": 2
   },
   {
    "rn": "vi7",
    "beats": 2,
    "bass": "7"
   },
   {
    "rn": "IV",
    "beats": 2
   },
   {
    "rn": "IV",
    "beats": 2,
    "bass": "7"
   },
   {
    "rn": "ii7",
    "beats": 2
   },
   {
    "rn": "ii7",
    "beats": 2,
    "bass": "7"
   }
  ],
  "src": "official",
  "note": "The bass walks straight down the C major scale: C, B, A, G, F, E, D, C. Half the chords are inversions that exist only to keep that line moving.",
  "spotify": "spotify:track:0ToY1kYe2SKJG4lRgnnYEh",
  "art": "https://i.scdn.co/image/ab67616d00001e026a6377c352fcdeb390dd86f5",
  "ug": "https://tabs.ultimate-guitar.com/tab/procol-harum/a-whiter-shade-of-pale-official-2145379"
 },
 {
  "id": "piano-man-billy-joel",
  "title": "Piano Man",
  "artist": "Billy Joel",
  "year": 1973,
  "key": "C",
  "tempo": 90,
  "section": "intro",
  "start": 0,
  "dur": 24,
  "level": 7,
  "chords": [
   {
    "rn": "I",
    "beats": 3
   },
   {
    "rn": "V",
    "beats": 3,
    "bass": "3"
   },
   {
    "rn": "IV",
    "beats": 3,
    "bass": "3"
   },
   {
    "rn": "I",
    "beats": 3,
    "bass": "5"
   },
   {
    "rn": "IV",
    "beats": 3
   },
   {
    "rn": "I",
    "beats": 3,
    "bass": "3"
   },
   {
    "rn": "II",
    "beats": 3
   },
   {
    "rn": "V",
    "beats": 3
   }
  ],
  "src": "official",
  "note": "A waltz with the bass descending C, B, A, G, F, E, D, G. Note the D major (II) near the end: a secondary dominant heading for V.",
  "spotify": "spotify:track:70C4NyhjD5OZUMzvWZ3njJ",
  "art": "https://i.scdn.co/image/ab67616d00001e02aff4aef671b2510be7c115b3",
  "ug": "https://tabs.ultimate-guitar.com/tab/billy-joel/piano-man-official-2418957"
 },
 {
  "id": "stairway-to-heaven-led-zeppelin",
  "title": "Stairway to Heaven",
  "artist": "Led Zeppelin",
  "year": 1971,
  "key": "A minor",
  "tempo": 72,
  "section": "intro",
  "start": 0,
  "dur": 23,
  "level": 7,
  "chords": [
   {
    "rn": "i",
    "beats": 4
   },
   {
    "rn": "i",
    "beats": 4,
    "bass": "M7"
   },
   {
    "rn": "i7",
    "beats": 4,
    "bass": "7"
   },
   {
    "rn": "IV",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "VImaj7",
    "beats": 4
   },
   {
    "rn": "VII",
    "beats": 2
   },
   {
    "rn": "i",
    "beats": 2
   }
  ],
  "src": "official",
  "note": "Chromatic descending bass: A, G#, G, F#, F. The chord names are almost beside the point; the bass line is the composition.",
  "spotify": "spotify:track:5CQ30WqJwcep0pYcV4AMNc",
  "art": "https://i.scdn.co/image/ab67616d00001e02c8a11e48c91a982d086afc69",
  "ug": "https://tabs.ultimate-guitar.com/tab/led-zeppelin/stairway-to-heaven-official-1911433"
 },
 {
  "id": "free-bird-lynyrd-skynyrd",
  "title": "Free Bird",
  "artist": "Lynyrd Skynyrd",
  "year": 1973,
  "key": "G",
  "tempo": 60,
  "section": "intro / verse",
  "start": 0,
  "dur": 24,
  "level": 7,
  "chords": [
   {
    "rn": "I",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4,
    "bass": "3"
   },
   {
    "rn": "vi",
    "beats": 4
   },
   {
    "rn": "bVII",
    "beats": 4
   },
   {
    "rn": "IV",
    "beats": 4
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "I-V/3-vi-bVII-IV-V. Bass walks G, F#, E, then F: a diatonic descent that borrows F major on the way.",
  "spotify": "spotify:track:5EWPGh7jbTNO2wakv8LjUI",
  "art": "https://i.scdn.co/image/ab67616d00001e02128450651c9f0442780d8eb8",
  "ug": "https://tabs.ultimate-guitar.com/tab/lynyrd-skynyrd/free-bird-official-2420559"
 },
 {
  "id": "tears-in-heaven-eric-clapton",
  "title": "Tears in Heaven",
  "artist": "Eric Clapton",
  "year": 1992,
  "key": "A",
  "tempo": 78,
  "section": "intro / chorus",
  "start": 0,
  "dur": 20,
  "level": 7,
  "chords": [
   {
    "rn": "I",
    "beats": 2
   },
   {
    "rn": "V",
    "beats": 2,
    "bass": "3"
   },
   {
    "rn": "vi",
    "beats": 2
   },
   {
    "rn": "I",
    "beats": 2,
    "bass": "5"
   },
   {
    "rn": "IV",
    "beats": 2,
    "bass": "3"
   },
   {
    "rn": "V",
    "beats": 4
   }
  ],
  "src": "official",
  "note": "Bass: A, G#, F#, E, F#, E. Three of the six chords are inversions, all there to make the bass step rather than leap.",
  "spotify": "spotify:track:1kgdslQYmeTR4thk9whoRw",
  "art": "https://i.scdn.co/image/ab67616d00001e0244cb13558d57f5a066fac381",
  "ug": "https://tabs.ultimate-guitar.com/tab/eric-clapton/tears-in-heaven-official-1934645"
 }
];
